#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║    MemOrg AI - Backend Deployment to Render               ║"
echo "║    Connecting Frontend + Backend Under One Product        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PRE-DEPLOYMENT CHECKLIST:"
echo "✅ Backend code pushed to GitHub"
echo "✅ OpenAI migration complete (GPT-4 + text-embedding-3-small)"
echo "✅ CORS configured for Vercel frontend"
echo "✅ Dynamic PORT configuration added"
echo "✅ Health check endpoint ready (/api/health)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 PHASE 2: DEPLOY BACKEND TO RENDER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "MANUAL STEPS (Follow carefully):"
echo ""
echo "1. Go to: https://render.com"
echo "   - Login or create free account"
echo ""
echo "2. Click 'New +' → 'Web Service'"
echo ""
echo "3. Connect GitHub Repository:"
echo "   - Click 'Connect GitHub'"
echo "   - Authorize Render"
echo "   - Select repository: team_P1"
echo "   - Branch: ramtrail"
echo ""
echo "4. Configure Service:"
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Name:            memorg-ai-backend                      │"
echo "   │ Region:          Oregon (US West)                       │"
echo "   │ Branch:          ramtrail                               │"
echo "   │ Root Directory:  enterprise-rag                         │"
echo "   │ Runtime:         Python 3                               │"
echo "   │ Build Command:   pip install -r requirements.txt        │"
echo "   │ Start Command:   python api_server.py                   │"
echo "   └─────────────────────────────────────────────────────────┘"
echo ""
echo "5. Environment Variables (Click 'Advanced' → 'Add Environment Variable'):"
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Key: OPENAI_API_KEY                                     │"
echo "   │ Value: sk-proj-...  (your OpenAI API key)              │"
echo "   └─────────────────────────────────────────────────────────┘"
echo ""
echo "6. Click 'Create Web Service'"
echo "   - Wait 3-5 minutes for deployment"
echo "   - Render will assign a URL like:"
echo "     https://memorg-ai-backend.onrender.com"
echo ""
echo "7. COPY THE BACKEND URL (you'll need it for Phase 3)"
echo ""

read -p "Press ENTER when backend deployment is complete and you have the URL..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 PHASE 3: CONNECT FRONTEND TO BACKEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Enter your Render backend URL (e.g., https://memorg-ai-backend.onrender.com): " BACKEND_URL

if [ -z "$BACKEND_URL" ]; then
    echo "❌ Backend URL is required. Exiting."
    exit 1
fi

echo ""
echo "Updating Vercel environment variable..."
echo ""
echo "MANUAL STEPS:"
echo ""
echo "1. Go to: https://vercel.com/sriram182719-gmailcoms-projects/enterprise-rag-frontend"
echo "2. Click 'Settings' → 'Environment Variables'"
echo "3. Add new variable:"
echo "   ┌─────────────────────────────────────────────────────────┐"
echo "   │ Key:         NEXT_PUBLIC_API_URL                        │"
echo "   │ Value:       $BACKEND_URL                               │"
echo "   │ Environment: ✓ Production ✓ Preview ✓ Development      │"
echo "   └─────────────────────────────────────────────────────────┘"
echo "4. Click 'Save'"
echo "5. Go to 'Deployments' → Click '...' on latest → 'Redeploy'"
echo ""

read -p "Press ENTER when Vercel redeploy is complete..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ PHASE 4: VERIFICATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Testing backend health..."
curl -s "$BACKEND_URL/api/health" | python3 -m json.tool || echo "⚠️  Backend not responding yet (may still be starting)"
echo ""
echo "Testing frontend..."
echo "Open: https://enterprise-rag-frontend-pux7d4p5y.vercel.app"
echo ""
echo "VERIFICATION CHECKLIST:"
echo "  ☐ Frontend loads without errors"
echo "  ☐ No CORS errors in browser console (F12)"
echo "  ☐ Chat input appears"
echo "  ☐ Type a test question and send"
echo "  ☐ AI response appears"
echo "  ☐ Sources display (if available)"
echo "  ☐ Confidence badge shows"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 DEPLOYMENT COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Your MemOrg AI platform is now live:"
echo ""
echo "🌐 Frontend: https://enterprise-rag-frontend-pux7d4p5y.vercel.app"
echo "⚙️  Backend:  $BACKEND_URL"
echo ""
echo "📊 Final Architecture:"
echo ""
echo "    User Browser"
echo "         ↓"
echo "    Vercel (Frontend - Next.js)"
echo "         ↓ HTTPS"
echo "    Render (Backend - Flask API)"
echo "         ↓ HTTPS"
echo "    OpenAI (GPT-4 + Embeddings)"
echo ""
echo "✨ ONE cohesive product experience!"
echo ""
echo "📖 For detailed docs, see: RENDER_DEPLOYMENT.md"
echo ""
